### ISSUE TITLE
Error line 38

### ISSUE THREAD

**Issue by Keopss** [geomoby/GeoDeals-android#1]
Hi! i have been test this sample and in line 38 import com.geomoby.GeoMoby; not working and all word in the code with GeoMoby not work.

Thank you!

**Comment by geomoby** [comment]
Hi Keopss,

Thanks for letting us know! It was due to a missing library. It should be fixed by now. Please try again and let us know!

-The GeoMoby Team

**Comment by Keopss** [comment]
Hi have tried now compiled but the app working but not running background service. I have tried to reboot device but show a popup and say: Geomoby App stopped

**Comment by geomoby** [comment]
Hi Keopss,

Can you please send an email to support@geomoby.com? I will ask our team to
review your current issue and unblock you.

Regards,

*- The GeoMoby Team*
