### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by bij-ace** [geomoby/GeoDeals-android#2]
im getting this error when i start/stop geo service:

java.lang.NoClassDefFoundError: com.geomoby.service.GeomobyNotifyService
            at com.geomoby.service.GeomobyNotifyServiceReceiver.onReceive(Unknown Source)

please help
thanks

**Comment by cbaudia** [comment]
Hi!

Can you please send your request to support@geomoby.com?

One of our developers will follow up with you and fix the issue.

Thanks.

**Comment by bij-ace** [comment]
ok please check your mail

**Comment by bij-ace** [comment]
problem solved in the last commit. thanks! :+1:
