### ISSUE TITLE
iBeacon not working

### ISSUE THREAD

**Issue by bij-ace** [geomoby/GeoDeals-android#3]
When i start geomoby it says: 

iBeaconReceiver Started!
Initialising GeoMoby location updates...

i'm receiving notifications from GeoMoby Outdoor Location service but indoor service is not giving any response.

Also, when i set outdoor=false and indoor=true, it is not working. it doesn't even show "iBeaconReceiver Started!"

**Comment by cbaudia** [comment]
Hi!

Thanks for contacting us.

Please make sure to use our latest version Android 2.7?

In the case of our hybrid mode (indoor & outdoor), for the first time you launch the app, you might experience a "warm-up" period of 2-3 minutes for our system to adjust to your context. Then it should work properly.

It that still does not work, please send an email with some stack trace to support@geomoby.com.

Thanks.

**Comment by cbaudia** [comment]
Please make sure that you add our iBeacon service to your Manifest file:
        <service android:name="com.geomoby.ibeacon.service.IBeaconService" />

Thanks.

**Comment by bij-ace** [comment]
thanks :)
